%Lisa Li, lsl62
%Comparison between VICON and SLAM pose

%reading data from VICON file
%export CSV file from Vicon, save as xls
filenameVICON = 'Take27.xls';
VICONdata = xlsread(filenameVICON);
%reading in columns for the positions of back left wheel and front
%right wheel VICON balls, format of VICON CSV is very consistent, 
%these vectors might need to be adjusted if a different youbot model is 
%used
xBackLeftWheel0 = VICONdata(:,6); 
yBackLeftWheel0 = VICONdata(:,7);
xFrontRightWheel0 = VICONdata(:,12);
yFrontRightWheel0 = VICONdata(:,13); 
%eliminiating non-numerical cells (consistent formatting)
xBackLeftWheel = xBackLeftWheel0(5:end); 
yBackLeftWheel = yBackLeftWheel0(5:end);
xFrontRightWheel = xFrontRightWheel0(5:end);
yFrontRightWheel = yFrontRightWheel0(5:end); 
%calculating the origin, origin is center of odometry
xOrigin = (xBackLeftWheel+xFrontRightWheel)./2./1000;
yOrigin = (yBackLeftWheel+yFrontRightWheel)./2./1000;

%reading data from textfile, textfile generated by rostopic /trajectory
%textfile is consistent, indices may need to be adjusted if different
%format is used 
[SLAMvect] = textread('poseoutput10.txt', '%s');
%skipping first 11 cells, these cells are a header for the ROS pose 
%output, after these cells the output follows a consistent pattern
SLAMvectnew = SLAMvect(12:end);
%initializing SLAM coordinate vectors with dummy first value 
xSLAM= [0];
ySLAM= [0]; 
%reading the relevant information from textfile into SLAM coordinate
%vectors
for i = 1:length(SLAMvectnew)
    %only care about the x and y of position that is outputted 
    if (strcmp(SLAMvectnew(i,1), 'position:'))
        if (strcmp(SLAMvectnew(i+1,1), 'x:'))
            xSLAM = [xSLAM(1,:),str2num(cell2mat(SLAMvectnew(i+2,1)))];
        end
        if (strcmp(SLAMvectnew(i+3,1), 'y:'))
            ySLAM = [ySLAM(1,:),str2num(cell2mat(SLAMvectnew(i+4,1)))];
        end
    end
end
%ignoring the dummy variable, xSLAM and ySLAM now contain the raw SLAM pose 
xSLAM = xSLAM(2:end);
ySLAM = ySLAM(2:end);

%angle between VICON coordinate system and Youbot coordinate system.
%Can be found by physically taking measurements or by estimatation from 
%map+trajectory image
theta = -89;
SLAMgraphRotated = zeros(2,length(xSLAM));
%rotating Youbot frame to match VICON frame
for i = 1:length(xSLAM)
   %rotation matrix calculation
   coord = ...
       [cosd(theta) sind(theta); -sind(theta) cosd(theta)]...
       *[xSLAM(i); ySLAM(i)]; 
   SLAMgraphRotated(1,i) = coord(1); 
   SLAMgraphRotated(2,i) = coord(2); 
end
%translating Youbot frame to match origins
xSLAMgraphTranslated = SLAMgraphRotated(1,:) + ...
    (xOrigin(1)-SLAMgraphRotated(1,1)); 
ySLAMgraphTranslated = SLAMgraphRotated(2,:) + ...
    (yOrigin(1)-SLAMgraphRotated(2,1)); 

%plotting 
clf
figure(1)
plot(xOrigin, yOrigin, 'bs', xSLAMgraphTranslated, ySLAMgraphTranslated,...
    'ro', 'MarkerSize',5,'LineWidth', 2);
%commented out for generation of actual image, used for rotation
%visualization
%plot(xOrigin, yOrigin, 'bs', SLAMgraphRotated(1,:), ...
%SLAMgraphRotated(2,:), 'ro', 'MarkerSize',5,'LineWidth', 2);
hold on
%commented out, used to plot origin while SLAM frame getting rotated
%plot(SLAMgraphRotated(1,1), SLAMgraphRotated(2,1), ...
%'gx','MarkerSize', 20, 'LineWidth', 7); 
plot(xOrigin(1), yOrigin(1), 'kx','MarkerSize', 25, 'LineWidth', 5); 
set(gca,'Box','on','LineWidth',1,'FontName','Helvetica','FontSize',14);
title('VICON to Gmapping Comparison');
xlabel('X Coordinates (m)'); 
ylabel('Y Coordinates (m)');
legend('VICON Coordinates', 'Gmapping Coordinates','Start Position', ...
    'Location', 'eastoutside'); 

